# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Carter Haid
title: Cyber Security Student
email: carter.haid@maine.edu
website: www.carterhaid.com
phone: (401) 346-1338

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: icansecurethat
github_username:  Carter-Haid
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: CarterHaid
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Carter and I'm a Cyber Security Student. As well as administrating systems I also have experience making software and web apps. I have worked at a number of companies gaining teamwork and leadership skills.
  I am most skilled in: <mark>Python</mark>, <mark>AWS</mark>, and <mark>Penetration Testing</mark>.
content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Campus Parking Project
        link: parkusm.com
        # link_text: Project Website
        additional_links:
          - title:  Carter-Haid/Park-USM
            icon: fab fa-github
            url: github.com/Carter-Haid/Park-USM
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
          # This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          The Campus Parking Project is a parking lot availability visualizer written in <mark>Python</mark> for the University of Southern Maine. I started this project as a way if learning <mark>Flask</mark> and it has since grown into a fully fledged progressive web app. I have learned many skills through this and been I'm very proud of having this in my portfolio.
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Tyler Technologies
        link: tylertech.com
        # link_text: boringcompany.com
        sub_title: Information Security Intern
        caption: May 2020 - August 2020
        quote: >
          Empowering the people who serve the public.
        description: | # this will include new lines to allow paragraphs
            My primary focus at Tyler Technologies was policy and procedure documentation. I had the oppertunity to work with multiple information security teams and document what they do on a day to day basis. I also got some awesome training about how to use <mark>Burp Suite</mark> for penetration testing and wrote their company wiki page for some newly developed Security Tools.
      - layout: left
        title: Northeast Bank
        link: northeastbank.com
        # link_text: boringcompany.com
        sub_title: Information Technology Intern
        caption: May 2019 - May 2020
        quote: >
          Personalized Service Across the Nation.
        description: | # this will include new lines to allow paragraphs
            I worked as a long term intern for Northeast Bank. I traveled western Maine completing tickets, making network fixes, and upgrading old infastructre. I also learned how to triage tickets and monitor the network for performance issues, security threats, or outages.
      - layout: left
        title: The Jackson Laboratory
        link: jax.org
        # link_text: boringcompany.com
        sub_title: Network Engineering Intern
        caption: May 2018 - September 2020
        quote: >
          Empowering the people who serve the public.
        description: | # this will include new lines to allow paragraphs
            My first summer internship after my freshman year of college. I Learned <mark>Extreme Networking</mark> and gained more exposure into how firewalls, load balancers, and WAP's work. I also helped to design and implement the data network in their newly constructed facility in Ellsworth, Maine.
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Southern Maine
        caption: 2017 - Present
        sub_title: BSc Cyber Security
        quote: >
          The University of Everyone.
        description: | # this will include new lines to allow paragraphs
          During my time at USM I learned many key skills including teamwork and dealing with tight deadlines. I also learned how to build community and work with people from all walks of live during my jobs as a *Resident Assistant*.
          I spent a lot of my free time working with the *Russell Scholars Program* taking on roles such as *Lead Peer Mentor* and *Program Advocate*.
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Working on Certifications... Right now I have: <mark>CompTIA Security+</mark> & <mark>AWS Cloud Practitioner</mark>
      - Advocating for USM's [Russell Scholars Program](https://usm.maine.edu/rscholar)
      - [Hiking](https://www.alltrails.com/members/carter-haid-1?ref=header) (Preferably Mountains)
      - Custom PC Building
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
